language: r
sudo: required
cache: packages

os:
  - linux
  - osx

before_install:
  - chmod "+x" ./travis_setup.sh
  - ./travis_setup.sh
  - env

# before_script:
  # - chmod "+x" ./build_ci_env.R
  # - Rscript ./build_ci_env.R

warnings_are_errors: false