language: r
sudo: required
cache: packages
r: release
os:
  - linux
  - osx

before_install:
  - chmod "+x" ./travis_setup.sh
  - ./travis_setup.sh


addons:
  apt:
    packages:
      - subversion
      - autoconf
      - build-essential
      - libtool
      - libmagick++-dev

warnings_are_errors: false

