language: r
sudo: required
cache: packages

os:
  - linux
  - osx

before_install:
  - chmod "+x" ./travis_setup.sh
  - ./travis_setup.sh
  - export PATH="$HOME/miniconda/bin:$PATH"

before_script:
  - chmod "+x" ./py_install.R
  - Rscript ./py_install.R

warnings_are_errors: false

after_sucess:
  - conda list -n rettest

after_failure:
  - conda list -n rettest
