context("Test reticulate")
library(reticulate)
reticulate::use_condaenv("seurat_py_deps")
print("first test")
reticulate::py_module_available("numpy")
expect_true(reticulate::py_module_available("numpy"))
expect_true(reticulate::py_module_available("scanpy"))
expect_true(reticulate::py_module_available("phate"))